sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t iggroup/docker-alpine-miniconda3 .

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push iggroup/docker-alpine-miniconda3